<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            'id' => '0e98767b-dacb-4999-bf9e-97a477ab835d',
            'name' => 'Bob Smith',
            'email' => 'bobsmith@gmail.com',
            'password' => bcrypt('secret'),
            'title' => 'Business analyst',
            'sector' => 'Information Technology',
            'state' => 'vic',
            'city' => 'Melbourne',
            'experience' => 3,
            'java' => 0,
            'python' => 0,
            'c' => 0,
            'csharp' => 0,
            'cplus' => 0,
            'php' => 0,
            'html' => 0,
            'css' => 0,
            'javascript' => 0,
            'sql' => 0,
            'unix' => 0,
            'winserver' => 0,
            'windesktop' => 0,
            'linuxdesktop' => 0,
            'macosdesktop' => 0,
            'pearl' => 0,
            'bash' => 0,
            'batch' => 0,
            'cisco' => 0,
            'office' => 0,
            'r' => 0,
            'go' => 0,
            'ruby' => 0,
            'asp' => 0,
            'scala' => 0
        ]);
        
        DB::table('users')->insert([
            'id' => '325308a1-5697-4656-861f-b250ea5d69cc',
            'name' => 'Dean Winchester',
            'email' => 'deanwinchester@live.com',
            'password' => bcrypt('secret'),
            'title' => 'Programmer',
            'sector' => 'Information Technology',
            'state' => 'wa',
            'city' => 'Perth',
            'experience' => 2,
            'java' => 0,
            'python' => 0,
            'c' => 0,
            'csharp' => 0,
            'cplus' => 0,
            'php' => 0,
            'html' => 0,
            'css' => 0,
            'javascript' => 0,
            'sql' => 0,
            'unix' => 0,
            'winserver' => 0,
            'windesktop' => 0,
            'linuxdesktop' => 0,
            'macosdesktop' => 0,
            'pearl' => 0,
            'bash' => 0,
            'batch' => 0,
            'cisco' => 0,
            'office' => 0,
            'r' => 0,
            'go' => 0,
            'ruby' => 0,
            'asp' => 0,
            'scala' => 0
        ]);
        
        DB::table('users')->insert([
            'id' => '75654176-de65-4cab-9f24-646762f27de0',
            'name' => 'Kara Danvers',
            'email' => 'karad@gmail.com',
            'password' => bcrypt('secret'),
            'title' => 'Software Developer',
            'sector' => 'Information Technology',
            'state' => 'sa',
            'city' => 'adelaide',
            'experience' => 5,
            'java' => 0,
            'python' => 0,
            'c' => 0,
            'csharp' => 0,
            'cplus' => 0,
            'php' => 0,
            'html' => 0,
            'css' => 0,
            'javascript' => 0,
            'sql' => 0,
            'unix' => 0,
            'winserver' => 0,
            'windesktop' => 0,
            'linuxdesktop' => 0,
            'macosdesktop' => 0,
            'pearl' => 0,
            'bash' => 0,
            'batch' => 0,
            'cisco' => 0,
            'office' => 0,
            'r' => 0,
            'go' => 0,
            'ruby' => 0,
            'asp' => 0,
            'scala' => 0
        ]);
        
        DB::table('users')->insert([
            'id' => 'ed914be7-e220-4d9c-beb7-e38c4bffd570',
            'name' => 'Alec Lightwood',
            'email' => 'alightwood@gmail.com',
            'password' => bcrypt('secret'),
            'title' => 'Consultant',
            'sector' => 'Information Technology',
            'state' => 'vic',
            'city' => 'Melbourne',
            'experience' => 4,
            'java' => 0,
            'python' => 0,
            'c' => 0,
            'csharp' => 0,
            'cplus' => 0,
            'php' => 0,
            'html' => 0,
            'css' => 0,
            'javascript' => 0,
            'sql' => 0,
            'unix' => 0,
            'winserver' => 0,
            'windesktop' => 0,
            'linuxdesktop' => 0,
            'macosdesktop' => 0,
            'pearl' => 0,
            'bash' => 0,
            'batch' => 0,
            'cisco' => 0,
            'office' => 0,
            'r' => 0,
            'go' => 0,
            'ruby' => 0,
            'asp' => 0,
            'scala' => 0
        ]);
        
        DB::table('users')->insert([
            'id' => 'e00f73aa-b92e-4a56-b7eb-a21eeb19a7ae',
            'name' => 'Jillian Banks',
            'email' => 'jillianbanks@gmail.com',
            'password' => bcrypt('secret'),
            'title' => 'Project Manager',
            'sector' => 'Information Technology',
            'state' => 'vic',
            'city' => 'Melbourne',
            'experience' => 1,
            'java' => 0,
            'python' => 0,
            'c' => 0,
            'csharp' => 0,
            'cplus' => 0,
            'php' => 0,
            'html' => 0,
            'css' => 0,
            'javascript' => 0,
            'sql' => 0,
            'unix' => 0,
            'winserver' => 0,
            'windesktop' => 0,
            'linuxdesktop' => 0,
            'macosdesktop' => 0,
            'pearl' => 0,
            'bash' => 0,
            'batch' => 0,
            'cisco' => 0,
            'office' => 0,
            'r' => 0,
            'go' => 0,
            'ruby' => 0,
            'asp' => 0,
            'scala' => 0
        ]);
    }
}
